# Jekyll 配置文件
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# 开启数学公式支持（通过 KaTeX）
kramdown:
  math_engine: katex

# 设置首页文件
defaults:
  - scope:
      path: ""
    values:
      layout: default
